# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f6b1ff7682ca4dc73437d220503ab8d7c8970cb12c70885355f6312a440b8e249a3c4a32807a97e53cbfcceaaef81f576568f64d75cce9720de7e346ec5d5e8c

test:
  secret_key_base: b777ee23abb95cba0acb7f5cab2e79569815b640481516095e348fc2eac214b391efaf9b0e60979e1e3a292cc9bc1ec90430f6045af28647b199e94f36036847

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
